name: Conventional Commits

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.json
