name: Lint and Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selene:
    name: selene
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: AlejandroSuero/selene-linter-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: lua/ plugin/

  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --color always --check lua/ plugin/
