name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: LuaRocks upload
        if: ${{ steps.release.outputs.release_created }}
        uses: nvim-neorocks/luarocks-tag-release@v7
        with:
          license: MIT
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
